name: RunicDoors
version: ${project.version}
main: com.runicrealms.runicdoors.RunicDoors
api-version: 1.15
authors: [ hidden1nin ]
description: Pretty Doors
softdepend:
  - RunicCore
commands:
  door:
    description: door commands